#!/bin/bash

# Rename this `cli` file to your project's domain (e.g. 'chess', 'skat',
# 'doppelkopf', or 'library'). Adjust the jar file name if necessary and
# replace the entry point with your application's main class.
java -cp target/chess-0.1.0.jar hwr.oop.Chess "$@"
